version: '3'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    restart: always
    ports:
      - "8081:8080"
    container_name: swagger-ui
    hostname: swagger-ui
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
      API_URL: http://localhost:8081/swagger.yaml
    networks:
     - my_networks

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    restart: always
    ports:
      - "8082:8080"
    container_name: swagger-editor
    hostname: swagger-editor
    networks:
     - my_networks

networks:
  my_networks:
