# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401
from enum import Enum  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_codegen.models.base_model_ import Model  # noqa: F401
from swagger_codegen import util  # noqa: F401


class Sort(Enum):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    USER_ID = "user_id"
    USERNAME = "username"
    USER_STATUS = "user_status"

    @classmethod
    def value_of(cls, value: str, default=None) -> Enum:
        for _, member in Sort.__members__.items():
            if member.value == value:
                return member
        return default

    def upper(self) -> str:
        return self.value.upper()  # pylint: disable=E1101

    def pascalcase(self) -> str:
        words = self.value.split("_")  # pylint: disable=E1101
        return "".join([word.title() for word in words])
